apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: menu
  namespace: menu
spec:
  chart:
    spec:
      version: ">=0.0.5"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: menu.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
